interviewbit/config/routes.rb
Rails.application.routes.draw do
  get 'hello_world', to: 'hello_world#index'
  root 'interviews#index'
  get 'new' => 'interviews#new'
  
  resources :interviews
  resources :users
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
  namespace :api do
  	namespace :v1 do
  		resources :interviews
  		resources :users
  	end
  end
  get '*path' , to: 'interviews#index' , via: :all
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

interviewbit/app/models/interview.rb
class Interview < ApplicationRecord
	validates :title, presence: true, length: { minimum: 3 }
	validates :start, presence: true
	validates :finish, presence: true
	has_and_belongs_to_many :users , -> { distinct }
	validate :atleast_2_users , on: :create
	validate :finish_after_start
	validate :start_after_now
	validate :available_users , on: :create
	private
		def atleast_2_users
			if users.size < 2
				errors.add(:minimum , "2 users are required")
			end 
		end
		def start_after_now
			if Time.now > (start.strftime("%Y-%m-%d %H:%M:%S") + " UTC")	
				errors.add(:start, "must be after the current datetime")
			end
		end
		def finish_after_start
			if (start.strftime("%Y-%m-%d %H:%M:%S") + " UTC") > (finish.strftime("%Y-%m-%d %H:%M:%S") + " UTC")
				errors.add(:finish, "must be after the start datetime")
			end
		end
		def available_users
			str=start.strftime("%Y-%m-%d %H:%M:%S") + " UTC"
			fns=finish.strftime("%Y-%m-%d %H:%M:%S") + " UTC"
			users.each do |u|
				uid=u.id
				inter = Interview.joins(:users).where("interviews_users.user_id = ?", uid )
				inter.each do |i|
					st=i.start
					fs=i.finish
					if ((st>=str && st<=fns) || (fs>=str && fs<=fns) || (st<=str && fs>=fns)) 
						errors.add(:user, String(u.name)+ " Unavailable")	
					end
				end
			end
		end
end

interviewbit/app/controllers/api/v1/interviews_controller.rb
module Api
  module V1  
    class InterviewsController < ApplicationController
      def index

        interviews=Interview.all
        interviews=interviews.sort_by{|i| i.start}.reverse
        interviews=interviews.sort_by{|i| i.finish}.reverse
        render json: InterviewSerializer.new(interviews).serialized_json
      end

      def show
        interview=Interview.find(params[:id])
        render json: InterviewSerializer.new(interview).serialized_json
      end

      private 
        def i_para
            params.require(:interview).permit(:title,:start,:finish)
        end 
        def check(uid,start,finish)
          start=start + " UTC"
          finish=finish + " UTC"
          usr=User.find(uid)
          ans = true
          inter = Interview.joins(:users).where("interviews_users.user_id = ?", uid )
            inter.each do |i|
              st=i.start
              fs=i.finish
              if ((st>=start && st<=finish) || (fs>=start && fs<=finish) || (st<=start && fs>=finish)) ==true
                ans = false 
              end
            end
            return ans
        end
        def insert_job(jid,iid)
          query = "insert into interviews_jobs values('" + jid + "'," + String(iid) +")"
          ActiveRecord::Base.connection.execute(query)
        end
        def delete_job(iid)
          query = "select * from interviews_jobs where interview_id =" + String(iid)
          rows = ActiveRecord::Base.connection.execute(query)
          rows.each do |r|
            jid=r[0]
            puts jid
            job = Sidekiq::ScheduledSet.new.find_job(jid)
            job.delete
          end
          query = "delete from interviews_jobs where interview_id =" + String(iid)
          ActiveRecord::Base.connection.execute(query)
        end
    end
  end
end

interviewbit/app/controllers/interviews_controller.rb
class InterviewsController < ApplicationController
  def index
    @i=Interview.all
    @i=@i.sort_by{|i| i.start}.reverse
    @i=@i.sort_by{|i| i.finish}.reverse
  end
  def show
    @i=Interview.find(params[:id])
    @u=@i.users  
  end
  def edit
    @i = Interview.find(params[:id])
  end
  def new
    @i=Interview.new
  end
  def create
    #params[:interview][:title]=strip(params[:interview][:title])
    params[:interview][:start]=params[:interview][:start]+" "+params[:interview][:start_time]
    params[:interview][:finish]=params[:interview][:finish]+" "+params[:interview][:finish_time]
    params[:interview][:users].shift
    @users=User.find(params[:interview][:users])
    @i=Interview.new(i_para)
    @i.users = @users
    if @i.save(context: :create)
      @u=User.joins(:interviews).where("interviews_users.interview_id = ?", @i.id)
      arg = Array.new
      arg.append(@i.id)
      @u.each do |u|
        arg.append(u.id)
      end
      UserMailer.new_interview_email(@i.id).deliver_later
      cur_tim=Time.now.year*(60*24*365)+ (Time.now.month)*(60*24*30) + (Time.now.day)*(60*24) + (Time.now.hour)*(24) +(Time.now.strftime("%M").to_i)
      str_tim=@i.start.year*(60*24*365)+ (@i.start.month)*(60*24*30) + (@i.start.day)*(60*24) + (@i.start.hour)*(24) +(@i.start.strftime("%M").to_i)
      elapsed_minutes=str_tim-cur_tim- 720
      if elapsed_minutes < 0 
        elapsed_minutes = 0
      end
      job=UserMailer.reminder_email(@i.id).deliver_later(wait_until: elapsed_minutes.minutes.from_now)
      jid=job.provider_job_id
      insert_job(jid,@i.id)
      redirect_to '/'
    else
        render 'new'
    end
  end

  def update
    params[:interview][:start]=params[:interview][:start]+" "+params[:interview][:start_time]
    params[:interview][:finish]=params[:interview][:finish]+" "+params[:interview][:finish_time]
    params[:interview][:users].shift
    @i = Interview.find(params[:id])
    if params[:interview][:users].size < 2
      flash.now[:notice] = "Select atleast 2 Users."
      render 'edit' 
    else
      flag=false
      cur_usr=Array.new
        @i.users.each do |cu|
          cur_usr.append(cu.id)
      end
      query = "delete from interviews_users where interview_id = "+String(@i.id)
      ActiveRecord::Base.connection.execute(query)  
      cnt=1
      params[:interview][:users].each do |sel_usr|
        if check(sel_usr,params[:interview][:start],params[:interview][:finish]) ==false
          uid=sel_usr
          flash.now[cnt]= String(User.find(uid).name)+" is unavailable in this time slot"
          cnt=cnt+1
          flag=true
        end
      end
      if flag==true
        users=User.find(cur_usr)
        @i.users << users
        render 'edit'
      else
        users=User.find(params[:interview][:users])
        id=@i.id
        if @i.update(i_para)
          @i.users << users
          arg =Array.new
          arg.append(@i.title)
          arg.append(@i.start)
          arg.append(@i.finish)
          users.each do |u|
            arg.append(u.email)
          end
          UserMailer.update_interview_email(@i.id).deliver_later
          cur_tim=Time.now.year*(60*24*365)+ (Time.now.month)*(60*24*30) + (Time.now.day)*(60*24) + (Time.now.hour)*(24) +(Time.now.strftime("%M").to_i)
          str_tim=@i.start.year*(60*24*365)+ (@i.start.month)*(60*24*30) + (@i.start.day)*(60*24) + (@i.start.hour)*(24) +(@i.start.strftime("%M").to_i)
          elapsed_minutes=str_tim-cur_tim-720
          if elapsed_minutes < 0 
            elapsed_minutes = 0
          end
          delete_job(@i.id) 
          job = UserMailer.reminder_email(@i.id).deliver_later(wait_until: elapsed_minutes.minutes.from_now)
          jid=job.provider_job_id
          insert_job(jid,@i.id)
          redirect_to interviews_path
        else
          query = "delete from interviews_users where interview_id = "+String(@i.id)
          ActiveRecord::Base.connection.execute(query)
          users=User.find(cur_usr)
          @i.users << users
          render 'edit'
        end
      end
    end
  end

  def destroy
    @i = Interview.find(params[:id])
    @u=User.joins(:interviews).where("interviews_users.interview_id = ?", @i.id)
    arg = Array.new
    arg.append(@i.title)
    arg.append(@i.start)
    arg.append(@i.finish)
    @u.each do |u|
      arg.append(u.email)
    end
    delete_job(@i.id)
    @i.destroy
    UserMailer.with(arg: arg).destroy_interview_email.deliver_later
    redirect_to interviews_path
  end
  private 
    def i_para
        params.require(:interview).permit(:title,:start,:finish)
    end 
    def check(uid,start,finish)
      start=start + " UTC"
      finish=finish + " UTC"
      usr=User.find(uid)
      ans = true
      inter = Interview.joins(:users).where("interviews_users.user_id = ?", uid )
        inter.each do |i|
          st=i.start
          fs=i.finish
          if ((st>=start && st<=finish) || (fs>=start && fs<=finish) || (st<=start && fs>=finish)) ==true
            ans = false 
          end
        end
        return ans
    end
    def insert_job(jid,iid)
      query = "insert into interviews_jobs values('" + jid + "'," + String(iid) +")"
      ActiveRecord::Base.connection.execute(query)
    end
    def delete_job(iid)
      query = "select * from interviews_jobs where interview_id =" + String(iid)
      rows = ActiveRecord::Base.connection.execute(query)
      rows.each do |r|
        jid=r[0]
        puts jid
        job = Sidekiq::ScheduledSet.new.find_job(jid)
        job.delete
      end
      query = "delete from interviews_jobs where interview_id =" + String(iid)
      ActiveRecord::Base.connection.execute(query)
    end
end

interviewbit/app/helpers/interviews_helper.rb
module InterviewsHelper
end

interviewbit/app/views/interviews/create.html.erb
<h1>Interviews#create</h1>
<p>Find me in app/views/interviews/create.html.erb</p>

interviewbit/app/views/interviews/destroy.html.erb
<h1>Interviews#destroy</h1>
<p>Find me in app/views/interviews/destroy.html.erb</p>

interviewbit/app/views/interviews/edit.html.erb
<div style="width: 50%;" class="ml-auto mr-auto">
	<h3><%= link_to 'All Interviews', interviews_path ,class: 'btn btn-success' %></h3><br>
<h2>Edit Interview using the below form</h2>
	    <% flash.each do |type, msg| %>
      <h2>
        <%= msg %>
      </h2>
    <% end %>

		<% if @i.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@i.errors.count, "error") %> prohibited
        this Interview from being saved:
      </h2>
      <h3>
      <ul>
        <% @i.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
  </h3>
    </div>
  <% end %>
  <h4>
	<%= form_with(model: @i, local: true) do |f| %>

		<div>
			<%= f.label :title %><br>
		    <%= f.text_field :title   ,class: 'form-control'%>
		</div>
		  	
		<div>
			<%= f.label :start %>
			<%= f.date_field :start,  class: 'form-control' %>
		</div>
		<div>
			<%= f.label :start_time %>
			<% if @i.start? %>
				<%= f.time_field :start_time,  :value => @i.start.strftime("%H:%M:%S"),  class: 'form-control' %>
			<% else %>
				<%= f.time_field :start_time,  class: 'form-control' %>
			<%end%>
		</div>
		<div>
			<%= f.label :finish %>
			<%= f.date_field :finish,  class: 'form-control' %>
		</div>
		<div>
			<%= f.label :finish_time %>
			<% if @i.finish? %>
				<%= f.time_field :finish_time,  :value => @i.finish.strftime("%H:%M:%S"),  class: 'form-control' %>
			<% else %>
				<%= f.time_field :finish_time,  class: 'form-control' %>
			<%end%>
		</div><br>
		<div>
			<%= f.label :user %><br>
		    <p>Press Ctrl to select multiple users</p>
		    <%= f.collection_select :users , User.all , :id , :name, {include_blank: false , selected: @i.user_ids} , {multiple: true}    %>

		</div>
		<%= f.submit %>
	<% end %>
</h4>
</div>

interviewbit/app/views/interviews/index.html.erb
<!--<div class="justify-content-center ml-auto mr-auto container">

<h1>List of all interviews</h1>
	<h3>
		<%= link_to 'Schedule New Interview', new_interview_path , class: 'btn btn-success'%>
		<%= link_to 'View Users', users_path , class: 'btn btn-warning'%>
		<%= link_to 'Create New User', new_user_path , class: 'btn btn-success'%>
	</h3>
		<table class="table table-stripped">
		<thead>
			<td>Sr. No</td>
			<td>Title</td>
			<td >Start</td>
			<td >End</td>
			<td colspan="3">Actions</td>
		</thead>
		<% @cnt=0 %>
		<% @i.each do |i| %>
	    	<tr>
	    		<h4>
	    			<% @cnt=@cnt+1 %>
		    	<td><%= @cnt %></td>
		    	<td><%= i.title %></td>
		    	<td><%= i.start %> </td>
		    	<td><%= i.finish%> </td>
		    	<td><%= link_to 'View', '/interviews/'+String(i.id) , class: 'btn btn-success' %></td>
		    	<td><%= link_to 'Edit', edit_interview_url(i) , class: 'btn btn-warning' %></td>
		    	<td><%= link_to 'Delete', interviews_path+'/'+String(i.id), method: :delete, data: { confirm: 'Are you sure?' } , class: 'btn btn-danger' %></td>
		    	</h4>
		    </tr>
	    <%end%>
	    </table>

</div>-->

interviewbit/app/views/interviews/new.html.erb
<div class="justify-content-center ml-auto mr-auto container">
<h3><%= link_to 'Home', interviews_path , class: 'btn btn-success'%></h3>
<h1>New Interview Creation Page</h1>
<% if @i.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@i.errors.count, "error") %> prohibited
        this Interview from being saved:
      </h2>
      <h3>
      <ul>
        <% @i.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
  </h3>
    </div>
    <%end%>
<h4>
	<%= form_with(model: @i, local: true) do |f| %>
		<div>
			<%= f.label :title %>
			<%= f.text_field :title, class: 'form-control' %>
		</div>
		<div>
			<%= f.label :start %>
			<%= f.date_field :start,  class: 'form-control' %>
		</div>
		<div>
			<%= f.label :start_time %>
			<% if @i.start? %>
				<%= f.time_field :start_time,  :value => @i.start.strftime("%H:%M:%S"),  class: 'form-control' %>
			<% else %>
				<%= f.time_field :start_time,  class: 'form-control' %>
			<%end%>
		</div>
		<div>
			<%= f.label :finish %>
			<%= f.date_field :finish,  class: 'form-control' %>
		</div>
		<div>
			<%= f.label :finish_time %>
			<% if @i.finish? %>
				<%= f.time_field :finish_time,  :value => @i.finish.strftime("%H:%M:%S"),  class: 'form-control' %>
			<% else %>
				<%= f.time_field :finish_time,  class: 'form-control' %>
			<%end%>
		</div><br>
		<div>
			<%= f.label :user %><br>
		    <p>Press Ctrl to select multiple users</p>
		    <%= f.collection_select :users, User.all , :id , :name ,  {include_blank: false} , {multiple: true}    %>

		</div>
		<%= f.submit %>
	<%end%>
</h4>
</div>

interviewbit/app/views/interviews/show.html.erb
<div class="container ml-auto mr-auto">

	<div class="justify-content-center">
		<h3><%= link_to 'Home', interviews_path , class: 'btn btn-success'%></h3>
		<h1>View interview</h1>
		<h4>
			<div class="row">
		    	<div class="col-4 border border-dark">
		    	<%= @i.title %>	
		    	</div>
		    	<div class="col-4 border border-dark">
		    		<h3> From <br><%= @i.start %> to <br><%= @i.finish %></h3>
		    			
		    	</div>
		    	<div class="col-4 border border-dark">
		    			<% @u.each do |u| %>
		    				<%=link_to u.name , '/users/'+String(u.id) , class: 'form-control'%>
		    			<% end %>
		    		
		    	</div>
		    </div>
		</h4>
	    <br>
	    	<h4>
	    		<%= link_to 'Edit', edit_interview_url(@i) , class: 'btn btn-warning' %>
	    		<%= link_to 'Delete', interview_path(@i), method: :delete, data: { confirm: 'Are you sure?' } , class: 'btn btn-danger' %>
	    	</h4>
	</div>
</div>

interviewbit/app/views/interviews/update.html.erb
<h1>Interviews#update</h1>
<p>Find me in app/views/interviews/update.html.erb</p>