interviewbit/config/routes.rb
Rails.application.routes.draw do
  get 'hello_world', to: 'hello_world#index'
  root 'interviews#index'
  get 'new' => 'interviews#new'
  
  resources :interviews
  resources :users
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
  namespace :api do
  	namespace :v1 do
  		resources :interviews
  		resources :users
  	end
  end
  get '*path' , to: 'interviews#index' , via: :all
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

interviewbit/app/models/user.rb
class User < ApplicationRecord
	validates :name, presence: true, length: { minimum: 3 }
	has_one_attached :resume
	validates :resume, presence: true
	has_and_belongs_to_many :interviews 
end

interviewbit/app/controllers/api/v1/users_controller.rb
module Api
  module V1
    class UsersController < ApplicationController
      protect_from_forgery with: :null_session
      def index
        users=User.all
        users=users.sort_by{|u| u.interviews.count}.reverse
        render json: UserSerializer.new(users).serialized_json
      end 

      def show
        user=User.find(params[:id])
        render json: UserSerializer.new(user).serialized_json
      end
      def new
        render json: {name: 123}
      end
      def create
        user=User.new(u_para)
        if user.save
          UserMailer.welcome_email(@u.id).deliver_later
          render json: UserSerializer.new(user).serialized_json
        else
            render json: {error: user.errors.messages}, status: 422
        end
      end
      def update
        user = User.find(params[:id])
        if user.update(u_para)
          UserMailer.welcome_email(@u.id).deliver_later
          render json: UserSerializer.new(user).serialized_json
        else
            render json: {error: user.errors.messages}, status: 422
        end
      end

      def destroy
        user = User.find(params[:id])
        if user.destroy
          head :no_content
        else
            render json: {error: user.errors.messages}, status: 422
        end
      end
      private 
        def u_para
            params.require(:user).permit(:name,:email,:resume)
        end
    end
  end
end

interviewbit/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @u=User.all
  end

  def show
    @u=User.find(params[:id])
  end

  def create
    #params[:user][:name]=Strip(params[:user][:name])
    @u=User.new(u_para)
    if @u.save
      UserMailer.welcome_email(@u.id).deliver_later
      redirect_to users_path
    else
        render 'new'
    end
  end

  def new
    @u=User.new
  end
  def edit
    @u = User.find(params[:id])
  end
  def update
    @u = User.find(params[:id])
    if @u.update(u_para)
        redirect_to users_path
    else
      render 'edit'
    end

  end

  def destroy
    @u = User.find(params[:id])
    @u.destroy
    redirect_to users_path
  end
  private 
    def u_para
        params.require(:user).permit(:name,:email,:resume)
    end
  
end

interviewbit/app/helpers/users_helper.rb
module UsersHelper
end

interviewbit/app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

interviewbit/app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

interviewbit/app/views/users/edit.html.erb
<div style="width: 50%;" class="ml-auto mr-auto">
	<h3><%= link_to 'All Users', users_path ,class: 'btn btn-success' %></h3><br>
<h2>Edit User using the below form</h2>
		<% if @u.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@u.errors.count, "error") %> prohibited
        this User from being saved:
      </h2>
      <h3>
      <ul>
        <% @u.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
  </h3>
    </div>
  <% end %>

	<%= form_with(model: @u, local: true) do |f| %>

		  <div>
		    <%= f.label :name %><br>
		    <%= f.text_field :name ,class: 'form-control'%>
		  	</div>
		  	<div>
		    <%= f.label :email %><br>
		    <%= f.text_field :email ,class: 'form-control'%>
		  	</div>
		  <% if @u.resume.attached? %>
		  	<%= link_to 'View Resume', url_for(@u.resume) ,class: 'btn btn-success' %>
		  <%end%>
		  <p>
		  	<%= f.label :resume %><br>
		 	<%= f.file_field  :resume ,class: 'form-control' %>
		  </p>
		  <p>
		    <%= f.submit %>
		  </p>
	<% end %>

</div>

interviewbit/app/views/users/index.html.erb
<div class="justify-content-center ml-auto mr-auto container">

<h1>List of all Users</h1>
	<h3>
		<%= link_to 'Create New User', new_user_path , class: 'btn btn-success'%>
		<%= link_to 'View Interviews', interviews_path , class: 'btn btn-warning'%>
		<%= link_to 'Schedule New Interview', new_interview_path , class: 'btn btn-success'%>
	</h3>
		<table class="table table-stripped">
		<thead>
			<td>Sr. No</td>
			<td>Name</td>
			<td>Email</td>
			<td colspan="3">Actions</td>
		</thead>
		<% @cnt=0 %>
		<% @u.each do |u| %>
	    	<tr>
	    		<h4>
	    			<% @cnt=@cnt+1 %>
		    	<td><%= @cnt %></td>
		    	<td><%= u.name %></td>
		    	<td><%= u.email %> </td>
		    	<td><%= link_to 'View', '/users/'+String(u.id) , class: 'btn btn-success' %></td>
		    	<td><%= link_to 'Edit', edit_user_url(u) , class: 'btn btn-warning' %></td>
		    	<td><%= link_to 'Delete', users_path+'/'+String(u.id), method: :delete, data: { confirm: 'Are you sure?' } , class: 'btn btn-danger' %></td>
		    	</h4>
		    </tr>
	    <%end%>
	    </table>

</div>

interviewbit/app/views/users/new.html.erb
<div class="justify-content-center ml-auto mr-auto container">
<h3><%= link_to 'All Users', users_path , class: 'btn btn-success'%></h3>
<h1>New User Creation Page</h1>
<h4>
	<% if @u.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@u.errors.count, "error") %> prohibited
        this user from being saved:
      </h2>
      <h3>
      <ul>
        <% @u.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
  </h3>
    </div>
  <% end %>

	<%= form_with scope: :user , url: users_path, local: true do |f| %>
		<div>
			<%= f.label :name %>
			<%= f.text_field :name, class: 'form-control' %>
		</div>
		<div>
			<%= f.label :email %>
			<%= f.email_field :email,  class: 'form-control' %>
		</div>
		<div>
			<%= f.label :resume %><br>
		 	<%= f.file_field  :resume ,class: 'form-control' %>
		</div>
		<%= f.submit %>
	<%end%>
</h4>
</div>

interviewbit/app/views/users/show.html.erb
<div class="container ml-auto mr-auto">

	<div class="justify-content-center">
		<h3><%= link_to 'Home', interviews_path , class: 'btn btn-success'%></h3>
		<h1>View User</h1>
		<h4>

			<div class="row">
		    	<%= @u.name %>	
		    	<br>	
		    	<%= @u.email %> 
		    	<br>
		    	<% if @u.resume.attached? %>
	    			<%= link_to 'Resume' ,  url_for(@u.resume) %> 
	    		<%end%>	    			
		    </div>
		</h4>
	    <br>
	    	<h4>
	    		<%= link_to 'Edit', edit_user_url(@u) , class: 'btn btn-warning' %>
	    		<%= link_to 'Delete', user_path(@u), method: :delete, data: { confirm: 'Are you sure?' } , class: 'btn btn-danger' %>
	    	</h4>
	    	<br>
	    	<h3>Interviews for <%= @u.name%> </h3>
	    	<table class="table table-stripped">
	    		<thead>
	    			<td>Sr No.</td>
	    			<td>Interview</td>
	    		</thead>	
	    		<tbody>
	    			<% cnt=1 %>
	    			<% @u.interviews.each do |i| %>
	    				<tr>
	    					<td><%= cnt %><% cnt=cnt+1 %></td>
	    					<td><%= link_to i.title, '/interviews/'+String(i.id)  %></td>
	    				</tr>
	    			<% end %>
	    		</tbody>
	    	</table>
	</div>
</div>

interviewbit/app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>